language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  - cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
